services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  spring:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spring-app
      ports:
        - "8080:8080"
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - postgres
